import crypto from 'node:crypto';
import { SourceError, ERROR_MESSAGES } from './githubSource.js';

const ID = /^[1-9][0-9]{0,11}$/;
const KEY = /^[a-fA-F0-9]{64}$/;
const object = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);

function invalid(code, detail) {
  throw new SourceError(code, ERROR_MESSAGES[code], detail);
}

/** ManifestHub AppID JSON is data only. No Lua or source expressions are evaluated. */
export function generateLua(appid, buffer) {
  if (!ID.test(appid)) invalid('appid_invalido');
  let data;
  try { data = JSON.parse(buffer.toString('utf8')); }
  catch { invalid('lua_dados_invalidos'); }
  if (!object(data) || String(data.appid) !== appid) invalid('lua_dados_invalidos');
  const depots = data.depot ?? data.depots;
  if (!object(depots)) invalid('lua_dados_invalidos');
  const ids = Object.keys(depots).filter((id) => ID.test(id))
    .sort((a, b) => Number(a) - Number(b));
  if (!ids.length) invalid('lua_dados_incompletos', { motivo: 'sem_depots' });
  const missing = [];
  const entries = [];
  for (const id of ids) {
    const depot = depots[id];
    if (!object(depot)) invalid('lua_dados_invalidos', { depot: id });
    const key = depot.decryptionkey;
    const manifest = depot.manifests?.public?.gid;
    if (!key || !manifest) {
      missing.push({ depot: id, key: !key, manifest: !manifest });
      continue;
    }
    // Never accept a numeric gid: JSON numbers may already have lost precision.
    if (typeof key !== 'string' || !KEY.test(key) || typeof manifest !== 'string' ||
        !/^[1-9][0-9]{0,19}$/.test(manifest) || BigInt(manifest) > 18446744073709551615n) {
      invalid('lua_dados_invalidos', { depot: id });
    }
    entries.push({ id, key: key.toLowerCase(), manifest });
  }
  if (missing.length) invalid('lua_dados_incompletos', { depots: missing });
  const lines = [
    '-- Generated by Manifest Gate',
    `-- AppID: ${appid}; branch: public; depots: ${entries.length}`,
    '-- Versions and keys are taken from the source snapshot.',
    '',
  ];
  if (!ids.includes(appid)) lines.push(`addappid(${appid})`);
  for (const { id, key, manifest } of entries) {
    lines.push(`addappid(${id}, 1, "${key}")`, `setManifestid(${id}, "${manifest}")`);
  }
  const output = Buffer.from(lines.join('\n') + '\n');
  return {
    buffer: output,
    sha256: crypto.createHash('sha256').update(output).digest('hex'),
    depotCount: entries.length,
  };
}
